import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#003DA5",
          50: "#e6edf8",
          100: "#c0d0ef",
          200: "#97b1e4",
          300: "#6d91d9",
          400: "#4d79d1",
          500: "#2d61c9",
          600: "#1f53bb",
          700: "#0f42a6",
          800: "#003DA5",
          900: "#002d7a",
        },
        accent: {
          DEFAULT: "#FF6B00",
          50: "#fff3e6",
          100: "#ffe0bf",
          200: "#ffcc94",
          300: "#ffb769",
          400: "#ffa247",
          500: "#FF6B00",
          600: "#e65f00",
          700: "#cc5300",
          800: "#b34700",
          900: "#993b00",
        },
        background: "#FFF8F0",
        success: "#00A86B",
        danger: "#D63B3B",
        gold: "#FFD700",
        cream: "#FFF8F0",

        // MD3 design-system tokens (DESIGN.md)
        "primary-container":          "#003da5",
        "primary-fixed":              "#dbe1ff",
        "primary-fixed-dim":          "#b4c5ff",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#98b1ff",
        "on-primary-fixed":           "#00174b",
        "on-primary-fixed-variant":   "#033ea6",
        "inverse-primary":            "#b4c5ff",
        "secondary":                  "#a04100",
        "secondary-container":        "#fe6b00",
        "secondary-fixed":            "#ffdbcc",
        "secondary-fixed-dim":        "#ffb693",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#572000",
        "on-secondary-fixed":         "#351000",
        "on-secondary-fixed-variant": "#7a3000",
        "tertiary":                   "#452900",
        "tertiary-container":         "#643d00",
        "tertiary-fixed":             "#ffddb8",
        "tertiary-fixed-dim":         "#ffb95f",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#f8a110",
        "on-tertiary-fixed":          "#2a1700",
        "on-tertiary-fixed-variant":  "#653e00",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        "surface":                    "#f9f9f7",
        "surface-bright":             "#f9f9f7",
        "surface-dim":                "#dadad8",
        "surface-variant":            "#e2e3e1",
        "surface-tint":               "#2d58bf",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f4f4f2",
        "surface-container":          "#eeeeec",
        "surface-container-high":     "#e8e8e6",
        "surface-container-highest":  "#e2e3e1",
        "on-surface":                 "#1a1c1b",
        "on-surface-variant":         "#434653",
        "on-background":              "#1a1c1b",
        "outline":                    "#747684",
        "outline-variant":            "#c4c6d5",
        "inverse-surface":            "#2f3130",
        "inverse-on-surface":         "#f1f1ef",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Lora", "Georgia", "serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Noto Serif", "serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        "card":          "0px 2px 12px rgba(26, 28, 27, 0.06), 0px 1px 4px rgba(26, 28, 27, 0.04)",
        "card-hover":    "0px 8px 24px rgba(26, 28, 27, 0.10), 0px 2px 8px rgba(26, 28, 27, 0.06)",
        "card-ambient":  "0px 12px 32px rgba(26, 28, 27, 0.06)",
        "card-subtle":   "0px 4px 16px rgba(26, 28, 27, 0.04)",
        "card-light":    "0px 8px 24px rgba(26, 28, 27, 0.04)",
        "bottom-sheet":  "0px -8px 40px rgba(0, 0, 0, 0.1)",
        "flip-card":     "0px 12px 32px rgba(0, 41, 117, 0.15)",
        "float":         "0px 8px 32px rgba(26, 28, 27, 0.10), 0px 2px 8px rgba(26, 28, 27, 0.06)",
      },
      animation: {
        "float-up": "floatUp 1s ease-out forwards",
        "shake": "shake 0.5s ease-in-out",
        "pulse-flame": "pulseFlame 2s ease-in-out infinite",
        "slide-up": "slideUp 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "slide-down": "slideDown 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "scale-in": "scaleIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "draw-path": "drawPath 1.5s ease-in-out forwards",
        "heart-break": "heartBreak 0.5s ease-in-out forwards",
        "bounce-in": "bounceIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "pulse-ring": "pulseRing 2s ease-in-out infinite",
        "node-ring":  "nodeRing 2s ease-out infinite",
        "shimmer":    "shimmer 2s linear infinite",
      },
      keyframes: {
        floatUp: {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-60px)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-8px)" },
          "40%": { transform: "translateX(8px)" },
          "60%": { transform: "translateX(-6px)" },
          "80%": { transform: "translateX(6px)" },
        },
        pulseFlame: {
          "0%, 100%": { transform: "scale(1)", filter: "brightness(1)" },
          "50%": { transform: "scale(1.08)", filter: "brightness(1.15)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.7)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        drawPath: {
          "0%": { strokeDashoffset: "1000" },
          "100%": { strokeDashoffset: "0" },
        },
        heartBreak: {
          "0%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.3)" },
          "60%": { transform: "scale(0.8) rotate(10deg)" },
          "100%": { transform: "scale(0) rotate(20deg)", opacity: "0" },
        },
        bounceIn: {
          "0%": { transform: "scale(0.3)", opacity: "0" },
          "50%": { transform: "scale(1.1)" },
          "70%": { transform: "scale(0.95)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        pulseRing: {
          "0%":   { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(0, 41, 117, 0.7)" },
          "70%":  { transform: "scale(1)",    boxShadow: "0 0 0 12px rgba(0, 41, 117, 0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(0, 41, 117, 0)" },
        },
        nodeRing: {
          "0%":   { transform: "scale(1)",   opacity: "0.6" },
          "100%": { transform: "scale(1.3)", opacity: "0" },
        },
        shimmer: {
          "0%":   { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(400%)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};

export default config;
